# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/motorola/xpeng/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),xpeng)

$(call add-radio-file-sha1-checked,radio/bluetooth.img,8de576c684e782367be46cf5be1695a578f14401)
$(call add-radio-file-sha1-checked,radio/modem.img,6d4a2d1a437055b07d0389406b35cd45ec7857f0)
$(call add-radio-file-sha1-checked,radio/abl.img,26f4b197da2a073a22d6ba27b60cd9bffe7ffb85)
$(call add-radio-file-sha1-checked,radio/aop.img,4333c30fa2d63adbcf83c98b34e377afbb472d7e)
$(call add-radio-file-sha1-checked,radio/cpucp.img,5af06933cad130d291a70e0139aca92ee2cc7b56)
$(call add-radio-file-sha1-checked,radio/devcfg.img,4eb9f2038fbe7986b6da653c4ab56ba8600e7474)
$(call add-radio-file-sha1-checked,radio/dsp.img,9c0171a9573cb782f81e65a8b45d6540b0bc079d)
$(call add-radio-file-sha1-checked,radio/fsg.img,5257819707091131736f28a70cb85f2fec4d2f99)
$(call add-radio-file-sha1-checked,radio/hyp.img,a205e1bae8176f0b31a07a1388bb30f6e925909e)
$(call add-radio-file-sha1-checked,radio/keymaster.img,24f2ced43bbf13bb351ab964a047b0067b65b027)
$(call add-radio-file-sha1-checked,radio/logo.img,68b8d09b4b30445ff929c6ce0d6dfb31e9ecd56c)
$(call add-radio-file-sha1-checked,radio/prov.img,6d47dc9852e2ac906ea9b890d22066af675ddbbb)
$(call add-radio-file-sha1-checked,radio/qupfw.img,1446ea429db0ceb2905810394ff64e59a752c64e)
$(call add-radio-file-sha1-checked,radio/shrm.img,bf95f508b21f1656bfba1e8b27251686e200c3fb)
$(call add-radio-file-sha1-checked,radio/storsec.img,0a8a2ec08722bab005524f0284fa97b5957ff545)
$(call add-radio-file-sha1-checked,radio/tz.img,8abd61de5dbee7098bde4c6d824f0d77e13069b5)
$(call add-radio-file-sha1-checked,radio/uefisecapp.img,33de09750802ef0693cb649031531981452cb007)
$(call add-radio-file-sha1-checked,radio/xbl.img,541b1559fe3130ef4cdc395bcdd1fc4b79766f11)
$(call add-radio-file-sha1-checked,radio/xbl_config.img,476bb098758a9e4b4106aeac78d02c32e0cd85b0)

endif
