# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/motorola/xpeng/setup-makefiles.sh

AB_OTA_PARTITIONS += \
    bluetooth \
    modem \
    abl \
    aop \
    cpucp \
    devcfg \
    dsp \
    fsg \
    hyp \
    keymaster \
    logo \
    prov \
    qupfw \
    shrm \
    storsec \
    tz \
    uefisecapp \
    xbl \
    xbl_config
